# Generated by Django 6.0.8 on 2026-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='external_type',
            field=models.CharField(blank=True, choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('CENTRAL_ADMIN', 'Central Administrator'), ('SUB_ADMIN', 'Sub Administrator'), ('RESEARCHER', 'Researcher'), ('TECHNICIAN', 'Technician'), ('EXTERNAL', 'External User')], max_length=30, null=True),
        ),
    ]
