# Generated by Django 6.0.8 on 2026-08-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='storage_condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
